# Generated by Django 2.2.14 on 2020-08-25 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
                ('newsletter', models.ManyToManyField(related_name='tag', to='newsletters.Newsletter')),
            ],
        ),
    ]
